
# ─── Security headers ──────────────────────────────────────────────
# Applied globally to all responses

# Prevents the page from being embedded in an iframe on other domains
# Protects against clickjacking attacks
add_header X-Frame-Options "SAMEORIGIN" always;

# Prevents browsers from MIME-sniffing the content-type
# Stops browsers from interpreting files as a different type than declared
# e.g. prevents a .txt file from being executed as JavaScript
add_header X-Content-Type-Options "nosniff" always;

# Controls how much referrer info is sent with requests
# strict-origin-when-cross-origin: sends full URL within same origin,
# only the domain on cross-origin HTTPS→HTTPS, nothing on HTTPS→HTTP
add_header Referrer-Policy "strict-origin-when-cross-origin" always;

# Prevents the browser from loading any resource from origins not explicitly listed
# unsafe-inline is required for Angular Material inline styles
# sha256 hash locks the theme initialization script (dark/light mode) in index.html
#   → only this exact script is allowed inline; any other inline script will be blocked
# unsafe-hashes is required for inline event handlers generated by third-party libraries
#   → less secure than hashes alone; remove once offending lib is identified and patched
# add_header Content-Security-Policy "default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'; font-src 'self'; img-src 'self'; connect-src 'self';" always;
add_header Content-Security-Policy-Report-Only "
  default-src 'self';
  script-src 'self' 'sha256-m34iv5yqYrV2+GVM+mrldUkdF0zoR8dugBooWPqY3f0=' 'unsafe-hashes';
  style-src 'self' 'unsafe-inline';
  font-src 'self';
  img-src 'self' ;
  connect-src 'self';
" always;

# Forces browsers to use HTTPS for all future requests for 1 year (max-age=31536000)
# includeSubDomains extends this to all subdomains
# WARNING: only enable if HTTPS is guaranteed on all envs — cannot be undone easily
# In k8s, prefer setting this at the ingress level if TLS is terminated there
add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;
